defaults:
  - base_trainer_config

name: cot_0_shot_explicit
configs:
  epochs: 0
  gradient_accumulation_steps: 0
  fusion_strategy: ""
  cot_prompt: "Let's think step by step"
  explicit_evidence: True
  common_lora_config: null
  section_lora_config: null