defaults:
  - base_trainer_config

name: fine_tune
configs:
  epochs: 10
  gradient_accumulation_steps: 32
  lora_configs:
    r: 16
    lora_alpha: 32
    lora_dropout: 0.0
    target_modules: ["k_proj", "q_proj", "v_proj"]
