defaults:
  - base_trainer_config

name: icl_late_coupled_fusion_8_shot
configs:
  epochs: 0
  gradient_accumulation_steps: 0
  query_corpus_filename: data/train.json
  num_in_context_examples: 8
  fusion_strategy: late_coupled
  explicit_evidence: False