defaults:
  - base_instruction_config

instruction_template: "{icl_example}Evidence: {evidence}\nStatement: {statement}\nQuestion: Answer in 1 word. Is the statement a contradiction or an entailment?\nAnswer: "
