defaults:
  - base_instruction_config

instruction_template: "{icl_example}{evidence} Based on that paragraph can we conclude that this sentence is true? {statement}\nOPTIONS:\n- Contradiction\n- Entailment\n{cot_prompt}\nAnswer: "