defaults:
  - base_instruction_config

instruction_template: "{icl_example}Read the text and determine if the sentence is true: {evidence} Sentence: {statement}\nOPTIONS:\n- Contradiction\n- Entailment\n{cot_prompt}\nAnswer: "