defaults:
  - base_instruction_config

instruction_template: "{icl_example}Read the following paragraph and determine if the hypothesis is true: {evidence} Hypothesis: {statement}\nOPTIONS:\n- Contradiction\n- Entailment\n{cot_prompt}\nAnswer: "