defaults:
  - base_model_config

name: MistralLite-7b
pipeline: ChatModelPipeline
configs:
  model_name_or_path: amazon/MistralLite
  max_seq_len: 4096
  system_prompt: You are a clinician who check if there is a contradiction or an entailment between a section of a clinical trial report and a statement.
  temperature: 0.001
  top_p: 0
  top_k: 1
  repetition_penalty: 1
  pretrained_adapter_merging: svd
  pretrained_adapter_paths:
    - aryopg/MistralLite-7b_lora_contrastive
    - aryopg/MistralLite-7b_lora_common
