defaults:
  - base_config
  - data: nli4ct_practice
  - dataloader: baseline
  - model: clinical_llama
  - optimizer: adamw
  - lr_scheduler: warmup_linear_decay
  - experiment: null
  - _self_
  
hydra:
  output_subdir: null
random_seed: 1234

wandb_project: NLI4CT
wandb_entity: aryopg

debug: false