defaults:
  - base_retriever_config

name: CTRBM25OkapiDenseReranker
configs:
  k1: 1.5
  b: 0.75
  epsilon: 0.25
  top_k: 5
  dense_retriever_name: microsoft/BiomedNLP-BiomedBERT-base-uncased-abstract-fulltext
